export const DepartmentOptions = [
  "Administration",
  "Accounting",
  "Finance",
  "Human Resources (HR)",
  "Recruitment",
  "Operations",
  "Legal",
  "Information Technology (IT)",
  "Engineering",
  "Research & Development (R&D)",
  "Product Management",
  "Project Management",
  "Sales",
  "Marketing",
  "Business Development",
  "Customer Support",
  "Client Relations",
  "Public Relations (PR)",
  "Corporate Communications",
  "Design",
  "Creative",
  "UI/UX",
  "Quality Assurance (QA)",
  "Data Science",
  "Analytics",
  "Machine Learning / AI",
  "Cybersecurity",
  "Cloud Services",
  "Procurement",
  "Logistics",
  "Supply Chain Management",
  "Manufacturing",
  "Production",
  "Facilities Management",
  "Maintenance",
  "Healthcare / Medical",
  "Nursing",
  "Pharmacy",
  "Clinical Research",
  "Education & Training",
  "Library & Knowledge Management",
  "Compliance",
  "Risk Management",
  "Audit",
  "Strategy & Planning",
  "Investor Relations",
  "Innovation",
  "Sustainability / ESG",
  "Corporate Social Responsibility (CSR)",
];
export const ModesOptions = ["On-site", "Remote", "Hybrid"];
export const employmentTypesOptions = [
  "Full-time",
  "Part-time",
  "Contract",
  "Internship",
];
export const SkillsOptions = [
  // Programming & Software Development
  "3D Modeling",
  "Advanced Research",
  "Agile Methodology",
  "AI & Machine Learning",
  "Android Development",
  "Angular",
  "API Development",
  "AR/VR Development",
  "Artificial Intelligence (AI)",
  "Assembly Language",
  "ASP.NET",
  "Automation Testing",
  "AWS",
  "Backend Development",
  "Big Data",
  "Blockchain",
  "C",
  "C#",
  "C++",
  "Cloud Computing",
  "COBOL",
  "Computer Vision",
  "Cross-Platform Development",
  "Cybersecurity",
  "Data Engineering",
  "Data Science",
  "Data Structures & Algorithms",
  "Database Management",
  "Deep Learning",
  "DevOps",
  "Django",
  "Docker",
  "Embedded Systems",
  "Flutter",
  "Frontend Development",
  "Full-Stack Development",
  "Game Development",
  "Git/Version Control",
  "Go",
  "Google Cloud Platform",
  "GraphQL",
  "Haskell",
  "HTML/CSS",
  "iOS Development",
  "IoT Development",
  "Java",
  "JavaScript",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Linux/Unix Administration",
  "Machine Learning (ML)",
  "MATLAB",
  "Microservices",
  "Microsoft Azure",
  "Mobile App Development",
  "MongoDB",
  "Natural Language Processing",
  "Node.js",
  "NoSQL",
  "Objective-C",
  "Oracle",
  "Perl",
  "PHP",
  "PostgreSQL",
  "Python",
  "R Programming",
  "React",
  "React Native",
  "REST APIs",
  "Ruby",
  "Ruby on Rails",
  "Rust",
  "Salesforce Development",
  "Scala",
  "Software Architecture",
  "Software Development",
  "Software Testing & QA",
  "Spring Framework",
  "SQL",
  "Swift",
  "System Administration",
  "Terraform",
  "TypeScript",
  "UI/UX Design",
  "Unity",
  "Unreal Engine",
  "Vue.js",
  "Web Development",
  "WordPress Development",
  "Xamarin",

  // Business & Management
  "Accounting",
  "Accounting (CPA, CA)",
  "Adaptability",
  "Analytical Skills",
  "Auditing",
  "Brand Management",
  "Business Analysis",
  "Business Development",
  "Business Intelligence",
  "Business Intelligence (BI)",
  "Business Strategy",
  "Change Management",
  "Collaboration",
  "Communication Skills",
  "Conflict Resolution",
  "Contract Management",
  "Critical Thinking",
  "CRM",
  "Customer Relationship Management",
  "Customer Service",
  "Data-Driven Decision Making",
  "Decision Making",
  "Digital Transformation",
  "E-commerce Management",
  "Emotional Intelligence",
  "Entrepreneurship",
  "Executive Leadership",
  "Finance (CFA)",
  "Financial Analysis",
  "Financial Management",
  "Financial Planning",
  "Human Resource Management",
  "Innovation Management",
  "International Business",
  "Investment Management",
  "Kanban",
  "Leadership",
  "Lean Management",
  "Management Consulting",
  "Market Research",
  "Marketing",
  "Mergers & Acquisitions",
  "Negotiation",
  "Operations Management",
  "Organizational Development",
  "Performance Management",
  "Presentation Skills",
  "Problem Solving",
  "Product Management",
  "Project Management",
  "Project Management (PMP)",
  "Quality Assurance",
  "Risk Management",
  "Sales Management",
  "Scrum",
  "Six Sigma",
  "Strategic Planning",
  "Supply Chain Management",
  "Talent Acquisition",
  "Team Building",
  "Teamwork",
  "Time Management",
  "Training & Development",
  "Vendor Management",

  // Marketing & Digital
  "Affiliate Marketing",
  "Brand Strategy",
  "Community Management",
  "Content Creation",
  "Content Marketing",
  "Content Strategy",
  "Conversion Rate Optimization",
  "Copywriting",
  "Creative Writing",
  "Digital Analytics",
  "Digital Marketing",
  "Email Marketing",
  "Growth Hacking",
  "Influencer Marketing",
  "Market Analysis",
  "Marketing Automation",
  "Media Planning",
  "Online Advertising",
  "Paid Social Media",
  "Pay-Per-Click (PPC)",
  "Public Relations",
  "Search Engine Marketing (SEM)",
  "Search Engine Optimization (SEO)",
  "SEO/SEM",
  "Social Media Marketing",
  "Video Marketing",
  "Web Analytics",

  // Design & Creative
  "2D Animation",
  "3D Animation",
  "Adobe Creative Suite",
  "Animation",
  "Architectural Design",
  "Art Direction",
  "Branding Design",
  "CAD Design",
  "Character Design",
  "Color Theory",
  "Concept Art",
  "Creative Direction",
  "Fashion Design",
  "Game Design",
  "Graphic Design",
  "Illustration",
  "Industrial Design",
  "Interior Design",
  "Logo Design",
  "Motion Graphics",
  "Packaging Design",
  "Photography",
  "Print Design",
  "Product Design",
  "Sketch",
  "Typography",
  "User Experience (UX)",
  "User Interface (UI)",
  "Video Editing",
  "Visual Design",
  "Web Design",

  // Engineering & Technical
  "Aerospace Engineering",
  "Agricultural Engineering",
  "Automation Engineering",
  "Automotive Engineering",
  "Biomedical Engineering",
  "CAD/3D Modeling",
  "Chemical Engineering",
  "Civil Engineering",
  "Construction Management",
  "Control Systems",
  "Electrical Engineering",
  "Electronics Engineering",
  "Energy Engineering",
  "Engineering Design",
  "Environmental Engineering",
  "HVAC Systems",
  "Industrial Engineering",
  "Manufacturing Engineering",
  "Materials Science",
  "Mechanical Engineering",
  "Mining Engineering",
  "Nuclear Engineering",
  "Ocean Engineering",
  "Petroleum Engineering",
  "Process Engineering",
  "Quality Control",
  "Robotics",
  "Safety Engineering",
  "Structural Engineering",
  "Systems Engineering",
  "Telecommunications Engineering",
  "Transportation Engineering",

  // Healthcare & Medical
  "Anatomy & Physiology",
  "Anesthesiology",
  "Cardiology",
  "Clinical Research",
  "Dentistry",
  "Dermatology",
  "Emergency Medicine",
  "Epidemiology",
  "Gastroenterology",
  "Geriatrics",
  "Gynecology",
  "Healthcare Administration",
  "Healthcare Data Analytics",
  "Healthcare Management",
  "Medical Coding",
  "Medical Device Development",
  "Medical Imaging",
  "Medical Knowledge",
  "Medical Research",
  "Medical Writing",
  "Neurology",
  "Nursing",
  "Obstetrics",
  "Occupational Therapy",
  "Oncology",
  "Ophthalmology",
  "Orthopedics",
  "Pathology",
  "Patient Care",
  "Pediatrics",
  "Pharmacy",
  "Physical Therapy",
  "Psychiatry",
  "Psychology",
  "Public Health",
  "Public Health Analysis",
  "Radiology",
  "Rehabilitation",
  "Surgery",
  "Telemedicine",
  "Urology",
  "Veterinary Medicine",

  // Education & Training
  "Adult Education",
  "Assessment & Evaluation",
  "Classroom Management",
  "Corporate Training",
  "Curriculum Design",
  "Curriculum Development",
  "Distance Learning",
  "E-learning",
  "E-learning Development",
  "E-learning Tools",
  "Educational Technology",
  "Higher Education",
  "Instructional Design",
  "K-12 Education",
  "Learning Management Systems",
  "Lesson Planning",
  "Online Course Development",
  "Pedagogy",
  "Professional Development",
  "Special Education",
  "Student Assessment",
  "Teaching",
  "Training Facilitation",
  "Vocational Training",

  // Data & Analytics
  "Advanced Analytics",
  "Big Data Analytics",
  "Business Analytics",
  "Data Analysis",
  "Data Analytics",
  "Data Collection",
  "Data Mining",
  "Data Modeling",
  "Data Visualization",
  "Database Administration",
  "Database Design",
  "ETL Processes",
  "Market Research Analytics",
  "Predictive Analytics",
  "Quantitative Analysis",
  "Statistical Analysis",
  "Statistical Modeling",

  // Finance & Banking
  "Asset Management",
  "Banking Operations",
  "Capital Markets",
  "Commercial Banking",
  "Corporate Finance",
  "Credit Analysis",
  "Derivatives Trading",
  "Financial Modeling",
  "Financial Planning & Analysis",
  "Fixed Income",
  "Foreign Exchange",
  "Insurance",
  "Investment Banking",
  "Portfolio Management",
  "Private Equity",
  "Quantitative Finance",
  "Real Estate Finance",
  "Retail Banking",
  "Trading",
  "Treasury Management",
  "Underwriting",
  "Wealth Management",

  // Legal & Compliance
  "Commercial Law",
  "Compliance Management",
  "Constitutional Law",
  "Contract Law",
  "Corporate Law",
  "Criminal Law",
  "Employment Law",
  "Environmental Law",
  "Family Law",
  "Immigration Law",
  "Intellectual Property Law",
  "International Law",
  "Legal Research",
  "Legal Writing",
  "Litigation",
  "Patent Law",
  "Personal Injury Law",
  "Real Estate Law",
  "Regulatory Compliance",
  "Tax Law",

  // Media & Communications
  "Broadcast Journalism",
  "Communications Strategy",
  "Crisis Communication",
  "Digital Media",
  "Documentary Production",
  "Event Management",
  "Film Production",
  "Internal Communications",
  "Journalism",
  "Media Relations",
  "News Writing",
  "Photography",
  "Podcast Production",
  "Print Media",
  "Public Speaking",
  "Radio Production",
  "Scriptwriting",
  "Social Media Management",
  "Technical Writing",
  "Television Production",
  "Video Production",

  // Languages
  "Arabic",
  "Bengali",
  "Chinese (Mandarin)",
  "Chinese (Cantonese)",
  "Dutch",
  "English",
  "French",
  "German",
  "Greek",
  "Hebrew",
  "Hindi",
  "Italian",
  "Japanese",
  "Korean",
  "Norwegian",
  "Polish",
  "Portuguese",
  "Russian",
  "Spanish",
  "Swedish",
  "Thai",
  "Turkish",
  "Ukrainian",
  "Urdu",
  "Vietnamese",

  // Science & Research
  "Academic Research",
  "Academic Writing",
  "Astronomy",
  "Biochemistry",
  "Biology",
  "Biotechnology",
  "Botany",
  "Chemistry",
  "Clinical Research",
  "Data Collection & Analysis",
  "Ecology",
  "Environmental Science",
  "Genetics",
  "Geology",
  "Laboratory Techniques",
  "Marine Biology",
  "Mathematics",
  "Meteorology",
  "Microbiology",
  "Neuroscience",
  "Oceanography",
  "Physics",
  "Research",
  "Research Methodology",
  "Scientific Methods",
  "Scientific Writing",
  "Statistics",
  "Zoology",

  // Agriculture & Food
  "Agricultural Technology",
  "AgriTech Tools",
  "Animal Husbandry",
  "Crop Management",
  "Farm Management",
  "Food Processing",
  "Food Safety",
  "Food Science",
  "Horticulture",
  "Irrigation Systems",
  "Livestock Management",
  "Organic Farming",
  "Plant Breeding",
  "Soil Science",
  "Sustainable Agriculture",
  "Veterinary Science",

  // Manufacturing & Operations
  "Assembly Line Management",
  "Factory Management",
  "Industrial Automation",
  "Inventory Management",
  "Lean Manufacturing",
  "Logistics",
  "Manufacturing Processes",
  "Operations Research",
  "Production Planning",
  "Quality Management",
  "Supply Chain Optimization",
  "Warehouse Management",

  // Transportation & Logistics
  "Fleet Management",
  "Freight Management",
  "International Shipping",
  "Last-Mile Delivery",
  "Maritime Operations",
  "Rail Operations",
  "Route Optimization",
  "Transportation Planning",
  "Trucking Operations",

  // Retail & Sales
  "B2B Sales",
  "Category Management",
  "Customer Experience",
  "E-commerce",
  "Inside Sales",
  "Merchandising",
  "Outside Sales",
  "Retail Management",
  "Sales",
  "Sales Forecasting",
  "Visual Merchandising",

  // Hospitality & Tourism
  "Customer Service",
  "Event Planning",
  "Food & Beverage Management",
  "Hotel Management",
  "Restaurant Management",
  "Tourism Management",
  "Travel Planning",

  // Real Estate
  "Commercial Real Estate",
  "Property Development",
  "Property Management",
  "Real Estate Appraisal",
  "Real Estate Investment",
  "Residential Real Estate",

  // Energy & Environment
  "Energy Efficiency",
  "Environmental Consulting",
  "Environmental Impact Assessment",
  "Environmental Sustainability",
  "Renewable Energy",
  "Solar Energy",
  "Sustainability Consulting",
  "Waste Management",
  "Water Resource Management",
  "Wind Energy",

  // Security & Safety
  "Cybersecurity (CISSP)",
  "Emergency Management",
  "Fire Safety",
  "Information Security",
  "Occupational Safety",
  "Physical Security",
  "Risk Assessment",
  "Safety Training",
  "Security Analysis",

  // Emerging Technologies
  "5G Technology",
  "Artificial General Intelligence",
  "Augmented Reality (AR)",
  "Autonomous Vehicles",
  "Bioinformatics",
  "Biotechnology Research",
  "Cryptocurrency",
  "Digital Twins",
  "Drone Technology",
  "Edge Computing",
  "Gene Therapy",
  "Internet of Things (IoT)",
  "Nanotechnology",
  "Quantum Computing",
  "Robotic Process Automation (RPA)",
  "Smart Cities",
  "Space Technology",
  "Virtual Reality (VR)",

  // Soft Skills & Personal Development
  "Active Listening",
  "Cross-Cultural Communication",
  "Cross-Cultural Skills",
  "Cultural Sensitivity",
  "Customer Focus",
  "Flexibility",
  "Initiative",
  "Innovation",
  "Interpersonal Skills",
  "Networking",
  "Patience",
  "Persistence",
  "Reliability",
  "Resilience",
  "Self-Motivation",
  "Stress Management",
  "Work-Life Balance",

  // Specialized Industries
  "Aviation",
  "Defense & Military",
  "Fashion Industry",
  "Film & Entertainment",
  "Gaming Industry",
  "Government Relations",
  "Mining Operations",
  "Music Industry",
  "Non-Profit Management",
  "Oil & Gas",
  "Pharmaceutical Industry",
  "Publishing",
  "Sports Management",
  "Telecommunications",
  "Utilities Management",

  // Regional/Cultural Specializations
  "African Business Practices",
  "Asian Market Knowledge",
  "European Regulations",
  "Latin American Culture",
  "Middle Eastern Relations",
  "Nordic Business Culture",

  // Certifications & Professional Qualifications
  "Cloud Certifications (AWS, Azure, GCP)",
  "Data Science & AI Certifications",
  "Industry-Specific Certifications",
  "Professional Certifications",

  // Additional Technical Skills
  "General Computer Skills",
  "Hardware Troubleshooting",
  "Network Administration",
  "Systems Integration",
  "Technical Documentation",
  "Technical Skills",
  "Technical Support",
  "Technology Implementation",
];
export const IndustriesOptions = [
  "Information Technology (IT)",
  "Software Development",
  "Artificial Intelligence (AI) & Machine Learning (ML)",
  "Data Science & Analytics",
  "Cybersecurity",
  "Cloud Computing",
  "Telecommunications",
  "Electronics & Semiconductors",
  "Banking",
  "Financial Services",
  "Insurance",
  "Investment & Asset Management",
  "Accounting & Auditing",
  "Real Estate",
  "Consulting",
  "E-commerce",
  "Healthcare",
  "Pharmaceuticals",
  "Biotechnology",
  "Medical Devices",
  "Hospital & Clinical Services",
  "Public Health",
  "Fitness & Wellness",
  "Automotive",
  "Aerospace & Aviation",
  "Mechanical Engineering",
  "Civil Engineering & Construction",
  "Electrical & Electronics Engineering",
  "Chemical Engineering",
  "Industrial Manufacturing",
  "Renewable Energy",
  "Mining & Metals",
  "Education",
  "EdTech",
  "Research & Development (R&D)",
  "Training & Skill Development",
  "Media & Entertainment",
  "Film & Television",
  "Music Industry",
  "Publishing",
  "Advertising & Marketing",
  "Public Relations (PR)",
  "Gaming & Esports",
  "Retail",
  "Fast-Moving Consumer Goods (FMCG)",
  "Fashion & Apparel",
  "Food & Beverage",
  "Luxury Goods",
  "Transportation",
  "Shipping & Logistics",
  "Supply Chain Management",
  "Aviation Services",
  "Railways",
  "Automobile Services",
  "Oil & Gas",
  "Power Generation",
  "Renewable Energy (Solar, Wind, Hydro)",
  "Environmental Services",
  "Waste Management",
  "Water Resources",
  "Public Administration",
  "Defense & Military",
  "Law Enforcement",
  "Non-Governmental Organizations (NGOs)",
  "International Development",
  "Hospitality",
  "Travel & Tourism",
  "Hotels & Resorts",
  "Event Management",
  "Agriculture",
  "Food Processing",
  "AgriTech",
  "Forestry",
  "Fisheries",
  "Others",
];
export const QualificationsOptions = [
  "Diploma / Associate Degree",
  "High School / Secondary School",
  "Secondary School Certificate (SSC)",
  "Higher Secondary Certificate (HSC)",
  "General Education Development (GED)",
  "Diploma",
  "Vocational Training Certificate",
  "Technical Certificate",
  "Associate Degree",
  "Bachelor’s Degree",
  "Bachelor of Arts (BA)",
  "Bachelor of Science (BSc)",
  "Bachelor of Commerce (BCom)",
  "Bachelor of Engineering (BEng)",
  "Bachelor of Technology (BTech)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Computer Applications (BCA)",
  "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
  "Bachelor of Laws (LLB)",
  "Bachelor of Education (BEd)",
  "Master’s Degree",
  "Master of Arts (MA)",
  "Master of Science (MSc)",
  "Master of Commerce (MCom)",
  "Master of Engineering (MEng)",
  "Master of Technology (MTech)",
  "Master of Business Administration (MBA)",
  "Master of Computer Applications (MCA)",
  "Master of Laws (LLM)",
  "Master of Education (MEd)",
  "Doctoral Degree (PhD)",
  "Doctor of Medicine (MD)",
  "Doctor of Philosophy (PhD)",
  "Doctor of Business Administration (DBA)",
  "Doctor of Education (EdD)",
  "Doctor of Science (DSc)",
  "Chartered Accountant (CA)",
  "Certified Public Accountant (CPA)",
  "Chartered Financial Analyst (CFA)",
  "Project Management Professional (PMP)",
  "Six Sigma Certification",
  "Certified Information Systems Security Professional (CISSP)",
  "Cisco Certified Network Associate (CCNA)",
  "AWS Certified Solutions Architect",
  "Microsoft Certified: Azure Fundamentals",
  "Google Cloud Certified Professional",
  "Data Science Certification",
  "Machine Learning Certification",
  "Artificial Intelligence Certification",
];
export const StatusOptions = ["Active", "Closed", "Paused"];
export const GenderOptions = ["Male", "Female", "Both"];
export const ExperienceOptions = [
  "0–1 years",
  "1–2 years",
  "2–3 years",
  "3–5 years",
  "5–7 years",
  "7–10 years",
  "10–15 years",
  "15+ years",
];
export const HR_llm_model = [
  { label: "GPT-4o (Open-AI) (Recommended)", value: "openai-gpt-4o" },
  { label: "GPT-4o-Mini (Open-AI)", value: "openai-gpt-4o-mini" },
  { label: "Gemini-2.0-Flash (Gemini)", value: "gemini-gemini-2.0-flash" },
  {
    label: "Gemini-2.0-Flash-Lite (Gemini)",
    value: "gemini-gemini-2.0-flash-lite",
  },
];
export const CompanySizeOptions = [
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1001-5000",
  "5001-10000",
  "10000+",
];
export const InterviewMinutesOptions = ["15", "30", "45", "60"];
export const InterviewPlatformOptions = ["MIA"];
export const InterviewAvtarOptions = [
  { value: "professional_female", label: "Professional AI (Female)" },
  { value: "professional_male", label: "Professional AI (Male)" },
  { value: "without_agent", label: "Without Avatar" },
];
export const InterviewExpectOptions = [
  "Technical Skills",
  "Problem Solving",
  "Communication",
  "Critical Thinking",
  "Design",
  "Teamwork",
  "Leadership",
  "System Design",
  "Coding",
  "Cultural Fit",
  "Attitude",
];
export const CG_Personalized_Options = ["Name", "Phone Number", "City"];
export const CG_RCS_CTA_Options = [
  { title: "Buy Now", detail: "Direct purchase link" },
  { title: "Call Now", detail: "Phone number" },
  { title: "Learn More", detail: "summer" },
  { title: "Claim Offer", detail: "Promotional link" },
  { title: "Book Appointment", detail: "Booking system link" },
  { title: "Download App", detail: "App store link" },
];
export const CG_RCS_SUA_Options = [
  "Scroll",
  "Open App",
  "Open URL",
  "Share",
  "Download",
];
export const CG_RCS_SR_Options = [
  "Upgrade",
  "Latest",
  "Compare Plans",
  "More Info",
  "View Details",
];
export const SM_Level_Options = ["Easy", "Medium", "Hard"];
export const MX_InterviewAvtarOptions = [
  { value: "female", label: "Professional AI (Female)" },
  { value: "male", label: "Professional AI (Male)" },
  { value: "no_avatar", label: "Without Avatar" },
];
export const MX_InterviewLevel = ["Beginner", "Intermediate", "Advanced"];
export const CS_LessionPlannerOptions = ["Draft", "Ready to teach", "Completed"];
